// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: pdfgen.proto

package gpdf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenPdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HtmlContent   string                 `protobuf:"bytes,1,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"` // html 内容 [required]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenPdfRequest) Reset() {
	*x = GenPdfRequest{}
	mi := &file_pdfgen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenPdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenPdfRequest) ProtoMessage() {}

func (x *GenPdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdfgen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenPdfRequest.ProtoReflect.Descriptor instead.
func (*GenPdfRequest) Descriptor() ([]byte, []int) {
	return file_pdfgen_proto_rawDescGZIP(), []int{0}
}

func (x *GenPdfRequest) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

type GenPdfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfData       []byte                 `protobuf:"bytes,1,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"` // pdf 文件内容
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`                  // pdf 的 sha256 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenPdfResponse) Reset() {
	*x = GenPdfResponse{}
	mi := &file_pdfgen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenPdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenPdfResponse) ProtoMessage() {}

func (x *GenPdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdfgen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenPdfResponse.ProtoReflect.Descriptor instead.
func (*GenPdfResponse) Descriptor() ([]byte, []int) {
	return file_pdfgen_proto_rawDescGZIP(), []int{1}
}

func (x *GenPdfResponse) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

func (x *GenPdfResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

var File_pdfgen_proto protoreflect.FileDescriptor

const file_pdfgen_proto_rawDesc = "" +
	"\n" +
	"\fpdfgen.proto\x12\x04gpdf\"2\n" +
	"\rGenPdfRequest\x12!\n" +
	"\fhtml_content\x18\x01 \x01(\tR\vhtmlContent\"C\n" +
	"\x0eGenPdfResponse\x12\x19\n" +
	"\bpdf_data\x18\x01 \x01(\fR\apdfData\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha2562D\n" +
	"\rPdfGenService\x123\n" +
	"\x06GenPdf\x12\x13.gpdf.GenPdfRequest\x1a\x14.gpdf.GenPdfResponseB\vZ\tcftp/gpdfb\x06proto3"

var (
	file_pdfgen_proto_rawDescOnce sync.Once
	file_pdfgen_proto_rawDescData []byte
)

func file_pdfgen_proto_rawDescGZIP() []byte {
	file_pdfgen_proto_rawDescOnce.Do(func() {
		file_pdfgen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pdfgen_proto_rawDesc), len(file_pdfgen_proto_rawDesc)))
	})
	return file_pdfgen_proto_rawDescData
}

var file_pdfgen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pdfgen_proto_goTypes = []any{
	(*GenPdfRequest)(nil),  // 0: gpdf.GenPdfRequest
	(*GenPdfResponse)(nil), // 1: gpdf.GenPdfResponse
}
var file_pdfgen_proto_depIdxs = []int32{
	0, // 0: gpdf.PdfGenService.GenPdf:input_type -> gpdf.GenPdfRequest
	1, // 1: gpdf.PdfGenService.GenPdf:output_type -> gpdf.GenPdfResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pdfgen_proto_init() }
func file_pdfgen_proto_init() {
	if File_pdfgen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdfgen_proto_rawDesc), len(file_pdfgen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pdfgen_proto_goTypes,
		DependencyIndexes: file_pdfgen_proto_depIdxs,
		MessageInfos:      file_pdfgen_proto_msgTypes,
	}.Build()
	File_pdfgen_proto = out.File
	file_pdfgen_proto_goTypes = nil
	file_pdfgen_proto_depIdxs = nil
}
