// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: pdfgen.proto

package gpdf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdfGenService_GenPdf_FullMethodName = "/gpdf.PdfGenService/GenPdf"
)

// PdfGenServiceClient is the client API for PdfGenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfGenServiceClient interface {
	// 请求生成pdf
	GenPdf(ctx context.Context, in *GenPdfRequest, opts ...grpc.CallOption) (*GenPdfResponse, error)
}

type pdfGenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfGenServiceClient(cc grpc.ClientConnInterface) PdfGenServiceClient {
	return &pdfGenServiceClient{cc}
}

func (c *pdfGenServiceClient) GenPdf(ctx context.Context, in *GenPdfRequest, opts ...grpc.CallOption) (*GenPdfResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenPdfResponse)
	err := c.cc.Invoke(ctx, PdfGenService_GenPdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfGenServiceServer is the server API for PdfGenService service.
// All implementations must embed UnimplementedPdfGenServiceServer
// for forward compatibility.
type PdfGenServiceServer interface {
	// 请求生成pdf
	GenPdf(context.Context, *GenPdfRequest) (*GenPdfResponse, error)
	mustEmbedUnimplementedPdfGenServiceServer()
}

// UnimplementedPdfGenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdfGenServiceServer struct{}

func (UnimplementedPdfGenServiceServer) GenPdf(context.Context, *GenPdfRequest) (*GenPdfResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenPdf not implemented")
}
func (UnimplementedPdfGenServiceServer) mustEmbedUnimplementedPdfGenServiceServer() {}
func (UnimplementedPdfGenServiceServer) testEmbeddedByValue()                       {}

// UnsafePdfGenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfGenServiceServer will
// result in compilation errors.
type UnsafePdfGenServiceServer interface {
	mustEmbedUnimplementedPdfGenServiceServer()
}

func RegisterPdfGenServiceServer(s grpc.ServiceRegistrar, srv PdfGenServiceServer) {
	// If the following call panics, it indicates UnimplementedPdfGenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdfGenService_ServiceDesc, srv)
}

func _PdfGenService_GenPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenPdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfGenServiceServer).GenPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdfGenService_GenPdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfGenServiceServer).GenPdf(ctx, req.(*GenPdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PdfGenService_ServiceDesc is the grpc.ServiceDesc for PdfGenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfGenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpdf.PdfGenService",
	HandlerType: (*PdfGenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenPdf",
			Handler:    _PdfGenService_GenPdf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pdfgen.proto",
}
