// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: mbr.proto

package gmbr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GmbrService_ListMemberships_FullMethodName               = "/gmbr.GmbrService/ListMemberships"
	GmbrService_GetMembership_FullMethodName                 = "/gmbr.GmbrService/GetMembership"
	GmbrService_GetActiveMembership_FullMethodName           = "/gmbr.GmbrService/GetActiveMembership"
	GmbrService_ListUserMemberships_FullMethodName           = "/gmbr.GmbrService/ListUserMemberships"
	GmbrService_ListMembershipBillings_FullMethodName        = "/gmbr.GmbrService/ListMembershipBillings"
	GmbrService_ActivateMembership_FullMethodName            = "/gmbr.GmbrService/ActivateMembership"
	GmbrService_CancelMembership_FullMethodName              = "/gmbr.GmbrService/CancelMembership"
	GmbrService_AdminGrantMembership_FullMethodName          = "/gmbr.GmbrService/AdminGrantMembership"
	GmbrService_AdminRevokeMembership_FullMethodName         = "/gmbr.GmbrService/AdminRevokeMembership"
	GmbrService_AdminCreateMembershipConfig_FullMethodName   = "/gmbr.GmbrService/AdminCreateMembershipConfig"
	GmbrService_AdminUpdateMembershipConfig_FullMethodName   = "/gmbr.GmbrService/AdminUpdateMembershipConfig"
	GmbrService_AdminPurgeCandidateMembership_FullMethodName = "/gmbr.GmbrService/AdminPurgeCandidateMembership"
	GmbrService_ListMembershipMails_FullMethodName           = "/gmbr.GmbrService/ListMembershipMails"
	GmbrService_GetMembershipMailDetail_FullMethodName       = "/gmbr.GmbrService/GetMembershipMailDetail"
	GmbrService_RetryMembershipMail_FullMethodName           = "/gmbr.GmbrService/RetryMembershipMail"
	GmbrService_IgnoreMembershipMail_FullMethodName          = "/gmbr.GmbrService/IgnoreMembershipMail"
)

// GmbrServiceClient is the client API for GmbrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GmbrServiceClient interface {
	// === 会员方案（纯身份查询）===
	ListMemberships(ctx context.Context, in *ListMembershipsRequest, opts ...grpc.CallOption) (*ListMembershipsResponse, error)
	GetMembership(ctx context.Context, in *GetMembershipRequest, opts ...grpc.CallOption) (*Membership, error)
	// === 用户会员查询 ===
	GetActiveMembership(ctx context.Context, in *GetActiveMembershipRequest, opts ...grpc.CallOption) (*GetActiveMembershipResponse, error)
	ListUserMemberships(ctx context.Context, in *ListUserMembershipsRequest, opts ...grpc.CallOption) (*ListUserMembershipsResponse, error)
	// === 缴费记录 ===
	ListMembershipBillings(ctx context.Context, in *ListMembershipBillingsRequest, opts ...grpc.CallOption) (*ListMembershipBillingsResponse, error)
	// === 生命周期（由 gmall 调用）===
	ActivateMembership(ctx context.Context, in *ActivateMembershipRequest, opts ...grpc.CallOption) (*ActivateMembershipResponse, error)
	CancelMembership(ctx context.Context, in *CancelMembershipRequest, opts ...grpc.CallOption) (*CancelMembershipResponse, error)
	// === 管理员 ===
	AdminGrantMembership(ctx context.Context, in *AdminGrantMembershipRequest, opts ...grpc.CallOption) (*AdminGrantMembershipResponse, error)
	AdminRevokeMembership(ctx context.Context, in *AdminRevokeMembershipRequest, opts ...grpc.CallOption) (*AdminRevokeMembershipResponse, error)
	AdminCreateMembershipConfig(ctx context.Context, in *AdminCreateMembershipConfigRequest, opts ...grpc.CallOption) (*AdminCreateMembershipConfigResponse, error)
	AdminUpdateMembershipConfig(ctx context.Context, in *AdminUpdateMembershipConfigRequest, opts ...grpc.CallOption) (*AdminUpdateMembershipConfigResponse, error)
	AdminPurgeCandidateMembership(ctx context.Context, in *AdminPurgeCandidateMembershipRequest, opts ...grpc.CallOption) (*AdminPurgeCandidateMembershipResponse, error)
	// === 会员邮件管理 ===
	ListMembershipMails(ctx context.Context, in *ListMembershipMailsRequest, opts ...grpc.CallOption) (*ListMembershipMailsResponse, error)
	GetMembershipMailDetail(ctx context.Context, in *GetMembershipMailDetailRequest, opts ...grpc.CallOption) (*GetMembershipMailDetailResponse, error)
	RetryMembershipMail(ctx context.Context, in *RetryMembershipMailRequest, opts ...grpc.CallOption) (*RetryMembershipMailResponse, error)
	IgnoreMembershipMail(ctx context.Context, in *IgnoreMembershipMailRequest, opts ...grpc.CallOption) (*IgnoreMembershipMailResponse, error)
}

type gmbrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGmbrServiceClient(cc grpc.ClientConnInterface) GmbrServiceClient {
	return &gmbrServiceClient{cc}
}

func (c *gmbrServiceClient) ListMemberships(ctx context.Context, in *ListMembershipsRequest, opts ...grpc.CallOption) (*ListMembershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembershipsResponse)
	err := c.cc.Invoke(ctx, GmbrService_ListMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) GetMembership(ctx context.Context, in *GetMembershipRequest, opts ...grpc.CallOption) (*Membership, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Membership)
	err := c.cc.Invoke(ctx, GmbrService_GetMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) GetActiveMembership(ctx context.Context, in *GetActiveMembershipRequest, opts ...grpc.CallOption) (*GetActiveMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveMembershipResponse)
	err := c.cc.Invoke(ctx, GmbrService_GetActiveMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) ListUserMemberships(ctx context.Context, in *ListUserMembershipsRequest, opts ...grpc.CallOption) (*ListUserMembershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserMembershipsResponse)
	err := c.cc.Invoke(ctx, GmbrService_ListUserMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) ListMembershipBillings(ctx context.Context, in *ListMembershipBillingsRequest, opts ...grpc.CallOption) (*ListMembershipBillingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembershipBillingsResponse)
	err := c.cc.Invoke(ctx, GmbrService_ListMembershipBillings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) ActivateMembership(ctx context.Context, in *ActivateMembershipRequest, opts ...grpc.CallOption) (*ActivateMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateMembershipResponse)
	err := c.cc.Invoke(ctx, GmbrService_ActivateMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) CancelMembership(ctx context.Context, in *CancelMembershipRequest, opts ...grpc.CallOption) (*CancelMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMembershipResponse)
	err := c.cc.Invoke(ctx, GmbrService_CancelMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) AdminGrantMembership(ctx context.Context, in *AdminGrantMembershipRequest, opts ...grpc.CallOption) (*AdminGrantMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminGrantMembershipResponse)
	err := c.cc.Invoke(ctx, GmbrService_AdminGrantMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) AdminRevokeMembership(ctx context.Context, in *AdminRevokeMembershipRequest, opts ...grpc.CallOption) (*AdminRevokeMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRevokeMembershipResponse)
	err := c.cc.Invoke(ctx, GmbrService_AdminRevokeMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) AdminCreateMembershipConfig(ctx context.Context, in *AdminCreateMembershipConfigRequest, opts ...grpc.CallOption) (*AdminCreateMembershipConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminCreateMembershipConfigResponse)
	err := c.cc.Invoke(ctx, GmbrService_AdminCreateMembershipConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) AdminUpdateMembershipConfig(ctx context.Context, in *AdminUpdateMembershipConfigRequest, opts ...grpc.CallOption) (*AdminUpdateMembershipConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpdateMembershipConfigResponse)
	err := c.cc.Invoke(ctx, GmbrService_AdminUpdateMembershipConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) AdminPurgeCandidateMembership(ctx context.Context, in *AdminPurgeCandidateMembershipRequest, opts ...grpc.CallOption) (*AdminPurgeCandidateMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPurgeCandidateMembershipResponse)
	err := c.cc.Invoke(ctx, GmbrService_AdminPurgeCandidateMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) ListMembershipMails(ctx context.Context, in *ListMembershipMailsRequest, opts ...grpc.CallOption) (*ListMembershipMailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembershipMailsResponse)
	err := c.cc.Invoke(ctx, GmbrService_ListMembershipMails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) GetMembershipMailDetail(ctx context.Context, in *GetMembershipMailDetailRequest, opts ...grpc.CallOption) (*GetMembershipMailDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMembershipMailDetailResponse)
	err := c.cc.Invoke(ctx, GmbrService_GetMembershipMailDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) RetryMembershipMail(ctx context.Context, in *RetryMembershipMailRequest, opts ...grpc.CallOption) (*RetryMembershipMailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryMembershipMailResponse)
	err := c.cc.Invoke(ctx, GmbrService_RetryMembershipMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gmbrServiceClient) IgnoreMembershipMail(ctx context.Context, in *IgnoreMembershipMailRequest, opts ...grpc.CallOption) (*IgnoreMembershipMailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IgnoreMembershipMailResponse)
	err := c.cc.Invoke(ctx, GmbrService_IgnoreMembershipMail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GmbrServiceServer is the server API for GmbrService service.
// All implementations must embed UnimplementedGmbrServiceServer
// for forward compatibility.
type GmbrServiceServer interface {
	// === 会员方案（纯身份查询）===
	ListMemberships(context.Context, *ListMembershipsRequest) (*ListMembershipsResponse, error)
	GetMembership(context.Context, *GetMembershipRequest) (*Membership, error)
	// === 用户会员查询 ===
	GetActiveMembership(context.Context, *GetActiveMembershipRequest) (*GetActiveMembershipResponse, error)
	ListUserMemberships(context.Context, *ListUserMembershipsRequest) (*ListUserMembershipsResponse, error)
	// === 缴费记录 ===
	ListMembershipBillings(context.Context, *ListMembershipBillingsRequest) (*ListMembershipBillingsResponse, error)
	// === 生命周期（由 gmall 调用）===
	ActivateMembership(context.Context, *ActivateMembershipRequest) (*ActivateMembershipResponse, error)
	CancelMembership(context.Context, *CancelMembershipRequest) (*CancelMembershipResponse, error)
	// === 管理员 ===
	AdminGrantMembership(context.Context, *AdminGrantMembershipRequest) (*AdminGrantMembershipResponse, error)
	AdminRevokeMembership(context.Context, *AdminRevokeMembershipRequest) (*AdminRevokeMembershipResponse, error)
	AdminCreateMembershipConfig(context.Context, *AdminCreateMembershipConfigRequest) (*AdminCreateMembershipConfigResponse, error)
	AdminUpdateMembershipConfig(context.Context, *AdminUpdateMembershipConfigRequest) (*AdminUpdateMembershipConfigResponse, error)
	AdminPurgeCandidateMembership(context.Context, *AdminPurgeCandidateMembershipRequest) (*AdminPurgeCandidateMembershipResponse, error)
	// === 会员邮件管理 ===
	ListMembershipMails(context.Context, *ListMembershipMailsRequest) (*ListMembershipMailsResponse, error)
	GetMembershipMailDetail(context.Context, *GetMembershipMailDetailRequest) (*GetMembershipMailDetailResponse, error)
	RetryMembershipMail(context.Context, *RetryMembershipMailRequest) (*RetryMembershipMailResponse, error)
	IgnoreMembershipMail(context.Context, *IgnoreMembershipMailRequest) (*IgnoreMembershipMailResponse, error)
	mustEmbedUnimplementedGmbrServiceServer()
}

// UnimplementedGmbrServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGmbrServiceServer struct{}

func (UnimplementedGmbrServiceServer) ListMemberships(context.Context, *ListMembershipsRequest) (*ListMembershipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemberships not implemented")
}
func (UnimplementedGmbrServiceServer) GetMembership(context.Context, *GetMembershipRequest) (*Membership, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembership not implemented")
}
func (UnimplementedGmbrServiceServer) GetActiveMembership(context.Context, *GetActiveMembershipRequest) (*GetActiveMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveMembership not implemented")
}
func (UnimplementedGmbrServiceServer) ListUserMemberships(context.Context, *ListUserMembershipsRequest) (*ListUserMembershipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserMemberships not implemented")
}
func (UnimplementedGmbrServiceServer) ListMembershipBillings(context.Context, *ListMembershipBillingsRequest) (*ListMembershipBillingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembershipBillings not implemented")
}
func (UnimplementedGmbrServiceServer) ActivateMembership(context.Context, *ActivateMembershipRequest) (*ActivateMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateMembership not implemented")
}
func (UnimplementedGmbrServiceServer) CancelMembership(context.Context, *CancelMembershipRequest) (*CancelMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMembership not implemented")
}
func (UnimplementedGmbrServiceServer) AdminGrantMembership(context.Context, *AdminGrantMembershipRequest) (*AdminGrantMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGrantMembership not implemented")
}
func (UnimplementedGmbrServiceServer) AdminRevokeMembership(context.Context, *AdminRevokeMembershipRequest) (*AdminRevokeMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminRevokeMembership not implemented")
}
func (UnimplementedGmbrServiceServer) AdminCreateMembershipConfig(context.Context, *AdminCreateMembershipConfigRequest) (*AdminCreateMembershipConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminCreateMembershipConfig not implemented")
}
func (UnimplementedGmbrServiceServer) AdminUpdateMembershipConfig(context.Context, *AdminUpdateMembershipConfigRequest) (*AdminUpdateMembershipConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpdateMembershipConfig not implemented")
}
func (UnimplementedGmbrServiceServer) AdminPurgeCandidateMembership(context.Context, *AdminPurgeCandidateMembershipRequest) (*AdminPurgeCandidateMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminPurgeCandidateMembership not implemented")
}
func (UnimplementedGmbrServiceServer) ListMembershipMails(context.Context, *ListMembershipMailsRequest) (*ListMembershipMailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembershipMails not implemented")
}
func (UnimplementedGmbrServiceServer) GetMembershipMailDetail(context.Context, *GetMembershipMailDetailRequest) (*GetMembershipMailDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembershipMailDetail not implemented")
}
func (UnimplementedGmbrServiceServer) RetryMembershipMail(context.Context, *RetryMembershipMailRequest) (*RetryMembershipMailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryMembershipMail not implemented")
}
func (UnimplementedGmbrServiceServer) IgnoreMembershipMail(context.Context, *IgnoreMembershipMailRequest) (*IgnoreMembershipMailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IgnoreMembershipMail not implemented")
}
func (UnimplementedGmbrServiceServer) mustEmbedUnimplementedGmbrServiceServer() {}
func (UnimplementedGmbrServiceServer) testEmbeddedByValue()                     {}

// UnsafeGmbrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GmbrServiceServer will
// result in compilation errors.
type UnsafeGmbrServiceServer interface {
	mustEmbedUnimplementedGmbrServiceServer()
}

func RegisterGmbrServiceServer(s grpc.ServiceRegistrar, srv GmbrServiceServer) {
	// If the following call panics, it indicates UnimplementedGmbrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GmbrService_ServiceDesc, srv)
}

func _GmbrService_ListMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).ListMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_ListMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).ListMemberships(ctx, req.(*ListMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_GetMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).GetMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_GetMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).GetMembership(ctx, req.(*GetMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_GetActiveMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).GetActiveMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_GetActiveMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).GetActiveMembership(ctx, req.(*GetActiveMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_ListUserMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).ListUserMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_ListUserMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).ListUserMemberships(ctx, req.(*ListUserMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_ListMembershipBillings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembershipBillingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).ListMembershipBillings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_ListMembershipBillings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).ListMembershipBillings(ctx, req.(*ListMembershipBillingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_ActivateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).ActivateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_ActivateMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).ActivateMembership(ctx, req.(*ActivateMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_CancelMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).CancelMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_CancelMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).CancelMembership(ctx, req.(*CancelMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_AdminGrantMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGrantMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).AdminGrantMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_AdminGrantMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).AdminGrantMembership(ctx, req.(*AdminGrantMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_AdminRevokeMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRevokeMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).AdminRevokeMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_AdminRevokeMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).AdminRevokeMembership(ctx, req.(*AdminRevokeMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_AdminCreateMembershipConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCreateMembershipConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).AdminCreateMembershipConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_AdminCreateMembershipConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).AdminCreateMembershipConfig(ctx, req.(*AdminCreateMembershipConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_AdminUpdateMembershipConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateMembershipConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).AdminUpdateMembershipConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_AdminUpdateMembershipConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).AdminUpdateMembershipConfig(ctx, req.(*AdminUpdateMembershipConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_AdminPurgeCandidateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPurgeCandidateMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).AdminPurgeCandidateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_AdminPurgeCandidateMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).AdminPurgeCandidateMembership(ctx, req.(*AdminPurgeCandidateMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_ListMembershipMails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembershipMailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).ListMembershipMails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_ListMembershipMails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).ListMembershipMails(ctx, req.(*ListMembershipMailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_GetMembershipMailDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipMailDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).GetMembershipMailDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_GetMembershipMailDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).GetMembershipMailDetail(ctx, req.(*GetMembershipMailDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_RetryMembershipMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryMembershipMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).RetryMembershipMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_RetryMembershipMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).RetryMembershipMail(ctx, req.(*RetryMembershipMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GmbrService_IgnoreMembershipMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IgnoreMembershipMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GmbrServiceServer).IgnoreMembershipMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GmbrService_IgnoreMembershipMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GmbrServiceServer).IgnoreMembershipMail(ctx, req.(*IgnoreMembershipMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GmbrService_ServiceDesc is the grpc.ServiceDesc for GmbrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GmbrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gmbr.GmbrService",
	HandlerType: (*GmbrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMemberships",
			Handler:    _GmbrService_ListMemberships_Handler,
		},
		{
			MethodName: "GetMembership",
			Handler:    _GmbrService_GetMembership_Handler,
		},
		{
			MethodName: "GetActiveMembership",
			Handler:    _GmbrService_GetActiveMembership_Handler,
		},
		{
			MethodName: "ListUserMemberships",
			Handler:    _GmbrService_ListUserMemberships_Handler,
		},
		{
			MethodName: "ListMembershipBillings",
			Handler:    _GmbrService_ListMembershipBillings_Handler,
		},
		{
			MethodName: "ActivateMembership",
			Handler:    _GmbrService_ActivateMembership_Handler,
		},
		{
			MethodName: "CancelMembership",
			Handler:    _GmbrService_CancelMembership_Handler,
		},
		{
			MethodName: "AdminGrantMembership",
			Handler:    _GmbrService_AdminGrantMembership_Handler,
		},
		{
			MethodName: "AdminRevokeMembership",
			Handler:    _GmbrService_AdminRevokeMembership_Handler,
		},
		{
			MethodName: "AdminCreateMembershipConfig",
			Handler:    _GmbrService_AdminCreateMembershipConfig_Handler,
		},
		{
			MethodName: "AdminUpdateMembershipConfig",
			Handler:    _GmbrService_AdminUpdateMembershipConfig_Handler,
		},
		{
			MethodName: "AdminPurgeCandidateMembership",
			Handler:    _GmbrService_AdminPurgeCandidateMembership_Handler,
		},
		{
			MethodName: "ListMembershipMails",
			Handler:    _GmbrService_ListMembershipMails_Handler,
		},
		{
			MethodName: "GetMembershipMailDetail",
			Handler:    _GmbrService_GetMembershipMailDetail_Handler,
		},
		{
			MethodName: "RetryMembershipMail",
			Handler:    _GmbrService_RetryMembershipMail_Handler,
		},
		{
			MethodName: "IgnoreMembershipMail",
			Handler:    _GmbrService_IgnoreMembershipMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mbr.proto",
}
